language: python
python:
  - "pypy3.5-5.10.1"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade setuptools tox tox-travis coveralls
dist: 
  - xenial
sudo:
  - required
script:
  - tox
after_success:
  - coveralls
